language: android
jdk:
  - oraclejdk8
dist: trusty
env:
  global:
    # The BuildTools version used by your project
    - ANDROID_BUILD_TOOLS=28.0.3
    - ANDROID_API=28
  matrix:
    - EMULATOR_API=21
    - EMULATOR_API=22
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
     - tools
     - platform-tools-$ANDROID_BUILD_TOOLS
     - build-tools-$ANDROID_BUILD_TOOLS
     - android-$ANDROID_API
     - android-$EMULATOR_API

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API
    - sys-img-armeabi-v7a-android-$EMULATOR_API

    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - yes | sdkmanager "platforms;android-$ANDROID_API"

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew lintDebug testDebugUnitTest connectedDebugAndroidTest

jobs:
  include:
    - stage: test
      script: echo "Done."
#      script: bash scripts/run-tests.sh
      on:
        all_branches: true